name: Hook
on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      workflow_run_id: ${{ steps.get_workflow_run_id.outputs.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Run bash script that triggers Python
        id: get_workflow_run_id
        env:
          GH_TOKEN: ${{ github.token }}
          repo_name: "projectsmahendra/testing-git"
          workflow_name: "hook.yml"
          branch: master
        run: |
          python3 trigger-workflow.py

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - name: Run bash script that triggers Python
        env:
          GH_TOKEN: ${{ github.token }}
          repo_name: "projectsmahendra/testing-git"
          INFRA_WORKFLOW_ID: ${{needs.job1.outputs.workflow_run_id}}
        run: |
          # chmod +x replace.sh    # Make the bash script executable
          # ./replace.sh           # Run the bash script
          echo "check status for workflow run = $INFRA_WORKFLOW_ID"
          python3 workflow-status.py