name: Hook
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ steps.set_job_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some tests
        run: |
          echo "Running job1"
          exit 1  # Simulate failure

      - name: Set job status
        id: set_job_status
        if: failure()  # This will be true if the job fails
        run: echo "::set-output name=status::failed"
      
      - name: Set success status
        id: set_job_status
        if: success()  # This will be true if the job succeeds
        run: echo "::set-output name=status::success"

  job2:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ steps.set_job_status.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some tests
        run: |
          echo "Running job2"

      - name: Set job status
        id: set_job_status
        if: failure()
        run: echo "::set-output name=status::failed"
      
      - name: Set success status
        id: set_job_status
        if: success()
        run: echo "::set-output name=status::success"

### 2. Use the last job to collect and print the failed jobs:

```yaml
  final_job:
    runs-on: ubuntu-latest
    needs: [job1, job2] # Add all jobs that this final job depends on
    steps:
      - name: Determine failed jobs
        run: |
          failed_jobs=()
          if [ "${{ needs.job1.outputs.job_status }}" == "failed" ]; then
            failed_jobs+=("job1")
          fi
          if [ "${{ needs.job2.outputs.job_status }}" == "failed" ]; then
            failed_jobs+=("job2")
          fi

          if [ ${#failed_jobs[@]} -eq 0 ]; then
            echo "All jobs passed!"
          else
            echo "The following jobs failed: ${failed_jobs[@]}"
          fi
