name: Hook
on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true
env:
  AUTH_TYPE: ${{ fromJson(inputs.arguments).auth_type }}
jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Set env NEED
        run: |
          echo "template name ${{ env.AUTH_TYPE }}"
          if [[ "${{ env.AUTH_TYPE }}" == "6" ]]; then
              echo "TEMPLATE_NAME='.NET 8.0 System API (AWS EKS)'" >> "$GITHUB_ENV"
          else
              echo "TEMPLATE_NAME='.NET 8.0 Expression API (AWS EKS)'" >> "$GITHUB_ENV"
          fi
          echo "output after ${{ env.TEMPLATE_NAME }}"
