name: Hook
on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true
env:
  OPTION_ONE: true
  OPTION_TWO: false
  OPTION_THREE: true

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Build Options JSON
        id: build_options_json
        run: |
          # Initialize an empty JSON object
          OPTIONS_JSON="{"

          # Append options as JSON properties based on conditions
          if [ "${OPTION_ONE}" == "true" ]; then
            OPTIONS_JSON="${OPTIONS_JSON}\"option_one\": true,"
          fi

          if [ "${OPTION_TWO}" == "true" ]; then
            OPTIONS_JSON="${OPTIONS_JSON}\"option_two\": true,"
          fi

          if [ "${OPTION_THREE}" == "true" ]; then
            OPTIONS_JSON="${OPTIONS_JSON}\"option_three\": true"
          fi

          # Close JSON object
          OPTIONS_JSON="${OPTIONS_JSON}}"

          # Export the built JSON as an output
          echo "options_json=$OPTIONS_JSON" >> $GITHUB_ENV

      - name: Print Options String
        run: echo "Built options string ${{ env.options }}"
