name: Hook
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true

jobs:
  set-output-job:
    runs-on: ubuntu-latest
    outputs: 
      OCTOPUS_PID: ${{ steps.create-octopus-project.outputs.octopus_pid }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Script to Set Outputs
        # shell: bash
        run: |
          python scripts/set_output.py
          # echo "=======${{ env.OCTOPUS_PID }}"
          
          # echo "octopus_pid=$(cat octopus_project_id.txt)"
          # echo "octopus_pid=$(cat octopus_project_id.txt)" >> $GITHUB_ENV

      - name: set output
        id: create-octopus-project
        run: echo "octopus_pid=${{ env.OCTOPUS_PID }}" >> $GITHUB_OUTPUT

      - name: RUN SCRIPT
        shell: bash
        run: |
          sh test.sh
        env:
          TESTVAR: bbb
          
          

  use-output-job:
    runs-on: ubuntu-latest
    needs: [set-output-job]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Outputs
        run: |
          echo "Output 1 is: ${{ needs.set-output-job.outputs.OCTOPUS_PID }}"
          echo "====== ${{ env.OCTOPUS_PID }}"

