name: Hook
on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true
env:
  Deploy_Eventbridge: false
  Deploy_Glue: true
  Deploy_Lambda: false
  Deploy_SNS: false
  Deploy_SQS: false
  Deploy_SF: false
  Deploy_S3: true
  Deploy_APIGW: true

jobs:
  set-output-job:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.set-output-step.outputs.output_1 }}
      output_2: ${{ steps.set-output-step.outputs.output_2 }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Script to Set Outputs
        id: set-output-step
        run: |
          python scripts/set_output.py
          # Read each line and set each output
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < output.txt

  use-output-job:
    runs-on: ubuntu-latest
    needs: set-output-job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Outputs
        run: |
          echo "Output 1 is: ${{ needs.set-output-job.outputs.output_1 }}"
          echo "Output 2 is: ${{ needs.set-output-job.outputs.output_2 }}"

