name: Hook
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some tests
        run: |
          echo "Running job1"
          exit 1  # Simulate failure

      - name: Set job status
        if: failure()  # This will be true if the job fails
        run: echo "sdfsd"
      
      - name: Set success status
        if: success()  # This will be true if the job succeeds
        run: echo "asdfdsf"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some tests
        run: |
          echo "Running job2"
      - name: Run some tests
        run: |
          echo "Running job2"
          exit 1  # Simulate failure

  final_job:
    runs-on: ubuntu-latest
    if: always()
    needs: [job1, job2] # Add all jobs that this final job depends on
    steps:
      - name: Determine failed jobs
        shell: bash
        run: |
          failed_jobs=()
          jobs=("${{ toJSON(needs) }}")

          for job in "${!jobs[@]}"; do
            result="${{ needs[$job].result }}"
            if [ "$result" == "failure" ]; then
              failed_jobs+=("$job")
            fi
          done

          if [ ${#failed_jobs[@]} -eq 0 ]; then
            echo "All jobs passed!"
          else
            echo "The following jobs failed: ${failed_jobs[@]}"
          fi
