name: Hook
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true
env:
  APPLICATION_TYPE: "2"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8'
      # - name: Install Dependencies
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     pip install pyyaml ruamel.yaml  # Install PyYAML

      - name: Run bash script that triggers Python
        run: |
          chmod +x replace.sh    # Make the bash script executable
          ./replace.sh           # Run the bash script
          

