name: Hook
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true

jobs:
  set-output-job:
    runs-on: ubuntu-latest
    outputs: 
      OCTOPUS_PIDX: ${{ steps.create-octopus-project.outputs.OCTOPUS_PIDD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Script to Set Outputs
        id: create-octopus-project
        shell: bash
        run: |
          python scripts/set_output.py
          # echo "=======${{ env.OCTOPUS_PID }}"
          echo "OCTOPUS_PIDD=${{ env.OCTOPUS_PID }}" >> $GITHUB_OUTPUT
          # echo "octopus_pid=$(cat octopus_project_id.txt)"
          # echo "octopus_pid=$(cat octopus_project_id.txt)" >> $GITHUB_ENV

      - run: echo ${{ env.OCTOPUS_PID }}
          

  use-output-job:
    runs-on: ubuntu-latest
    needs: [set-output-job]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Outputs
        run: |
          echo "Output 1 is: ${{ needs.set-output-job.outputs.OCTOPUS_PIDX }}"
          echo "====== ${{ env.OCTOPUS_PID }}"

