name: Hook
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Step 1: Run some tests
        id: step1
        run: |
          echo "Running Step 1"
          exit 1  # Simulate failure

      - name: Step 2: Build
        id: step2
        run: echo "Building project"

      - name: Step 3: Deploy
        id: step3
        run: echo "Deploying project"

      - name: Set failed step
        if: failure()
        run: echo "FAILED_STEP=${{ failure() && github.job }}" >> $GITHUB_ENV

  post-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print failed step
        run: |
          if [ -n "${{ env.FAILED_STEP }}" ]; then
            echo "The failed step was: ${{ env.FAILED_STEP }}"
          else
            echo "No steps failed."
          fi