name: Hook
on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Client JSON Payload'
        type: string
        default: '{}'
        required: true
env:
  OPTION_ONE: true
  OPTION_TWO: false
  OPTION_THREE: true

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Build Options String
        id: build_options
        run: |
          # Initialize an empty string for options
          OPTIONS=""

          # Append options based on conditions
          if [ "${OPTION_ONE}" == "true" ]; then
            OPTIONS="${OPTIONS} --option-one"
          fi

          if [ "${OPTION_TWO}" == "true" ]; then
            OPTIONS="${OPTIONS} --option-two"
          fi

          if [ "${OPTION_THREE}" == "true" ]; then
            OPTIONS="${OPTIONS} --option-three"
          fi

          # Export the built string as an output
          echo "options=$OPTIONS" >> $GITHUB_ENV

      - name: Print Options String
        run: echo "Built options string: ${{ env.options }}"
