name: Reuseable-workflow

on:
  workflow_dispatch:

jobs:
  job1:
    name: Call external workflow as job
    uses: projectsmahendra/XlsxWriter/.github/workflows/reusable.yml@master

  job2:
    name: Regular job
    runs-on: ubuntu-latest
    needs: job1
    if: always()  # ✅ Add this to run job2 even if job1 fails
    steps:
      - name: Say hello from job2
        run: echo "Hello from job2!"